export {default as Home} from './Home'
export {default as Layout} from './Layout'
export {default as About} from './About'  
export {default as Product} from './Product'  
export {default as Services} from './Services'  
